version: '3'

networks:
  bugtracker-network:
    driver: bridge
    name: bugtracker-network

services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./task1:/var/www:consistent
    networks:
      - bugtracker-network

  nginx:
    image: nginx:1.25.2
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
        - ./task1:/var/www
        - ./docker/nginx/:/etc/nginx/conf.d/
    links:
      - php
    depends_on:
      - php
    networks:
      - bugtracker-network
