name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v3
       
     - name: Create Tarball 
       run: | 
        mkdir ../build 
        cp -TR . ../build 
        tar -cvf deploy.tar ../build/ 
        ls

     - name: Copy Files To The Server
       uses: appleboy/scp-action@v0.1.7
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "deploy.tar"
          target: "/var/www/html"
          
     - name: Deploy The Code
       uses: appleboy/ssh-action@v0.1.4
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/html
            tar -xvf deploy.tar
            rm deploy.tar
